# Generated by Django 4.1.3 on 2022-11-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('price_per_tab', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IntakeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_time', models.CharField(max_length=50)),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_name', to='timeline_app.medicine')),
            ],
        ),
    ]
