# Generated by Django 4.1.3 on 2022-11-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeentry',
            name='medicine_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
